<?php

namespace d3yii2\d3pop3\command;

use d3system\commands\D3CommandController;
use d3yii2\d3pop3\components\DownloadFromUrlComponent;
use yii\db\Connection;

use function dump;

class DownloadAttachmentsController extends D3CommandController
{
    public function init(): void
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return Connection
     */
    public function getConnection(): Connection
    {
        return parent::getConnection();
    }

    /**
     * default action
     * @return int
     */
    public function actionIndex(): int
    {
        $downloadFromUrlComponent = new DownloadFromUrlComponent($this->getConnection());
        $getD3pop3Emails          = $downloadFromUrlComponent->getD3pop3EmailsWithSent();

        foreach ($getD3pop3Emails as $getD3pop3Email) {
           $response[] = $downloadFromUrlComponent->saveGlobalMask($getD3pop3Email);
        }


        return  1;
    }

}

