<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address type' => 'Adreses tips',
    'Body' => 'Pamatteksts',
    'Body Plain' => 'Vienkārš Pamatteksts',
    'Can not save attachment.' => 'Nevar saglabāt pielikumu.',
    'Company' => 'UZņēmums',
    'Connecting' => 'Pieslēgšanās',
    'Direction' => 'Virziens',
    'Email' => 'Epasts',
    'Email Container' => '',
    'Email Container ID' => '',
    'Email Datetime' => 'Epasta laiks',
    'Email ID' => '',
    'Email Id' => '',
    'Error: ' => 'Kļūda: ',
    'From' => 'No',
    'From Name' => 'No Vārd',
    'From User' => 'No Lietotāja',
    'Host' => 'Serveris',
    'ID' => '',
    'Message' => 'Ziņojums',
    'Model' => '',
    'Model ID' => '',
    'Model search field' => '',
    'Name' => 'Nosaukums',
    'None' => '',
    'Notes' => 'Piezīmes',
    'Password' => 'Parole',
    'Person' => 'Persona',
    'Please set email in My Company Email Settings' => 'Lūdzu, iestatiet epastu sadaļā Mani uzņēmuma e-pasta iestatījumi',
    'Port' => '',
    'Received' => 'Saņemts',
    'SSL' => '',
    'Search by email field' => 'Meklēt pēc epasta lauka',
    'Setting' => 'Uzstādījums',
    'Settings' => 'Uzstādījumi',
    'Status' => '',
    'Subject' => 'Tēma',
    'Sys Company ID' => '',
    'TLS' => '',
    'Time' => 'Laiks',
    'To' => 'Kam',
    'Type' => 'Tips',
    'Use SSL' => '',
    'User Name' => '',
    'Deleted' => 'Dzēsts',
    'Email: {email} has already been taken for type: {type}' => 'Šai epasta adresei: {email} jau eksistē konfigurācija priekš : {type}',
    'Mailbox Name' => 'Epasts',
];
