<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3pop3\models\base;

use Yii;

/**
 * This is the base-model class for table "d3pop3_email_models".
 *
 * @property string $id
 * @property string $email_id
 * @property string $model_name
 * @property string $model_id
 * @property string $status
 *
 * @property \d3yii2\d3pop3\models\D3pop3Email $email
 * @property string $aliasModel
 */
abstract class D3pop3EmailModel extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_NEW = 'New';
    const STATUS_READ = 'Read';
    const STATUS_DELETE = 'Delete';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'd3pop3_email_models';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email_id', 'model_id'], 'integer'],
            [['status'], 'string'],
            [['model_name'], 'string', 'max' => 50],
            [['email_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3pop3\models\D3pop3Email::className(), 'targetAttribute' => ['email_id' => 'id']],
            ['status', 'in', 'range' => [
                    self::STATUS_NEW,
                    self::STATUS_READ,
                    self::STATUS_DELETE,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3pop3', 'ID'),
            'email_id' => Yii::t('d3pop3', 'Email'),
            'model_name' => Yii::t('d3pop3', 'Model'),
            'model_id' => Yii::t('d3pop3', 'Model ID'),
            'status' => Yii::t('d3pop3', 'Status'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'email_id' => Yii::t('d3pop3', 'Email'),
            'model_name' => Yii::t('d3pop3', 'Model'),
            'model_id' => Yii::t('d3pop3', 'Model ID'),
            'status' => Yii::t('d3pop3', 'Status'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmail()
    {
        return $this->hasOne(\d3yii2\d3pop3\models\D3pop3Email::className(), ['id' => 'email_id']);
    }




    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_NEW => Yii::t('d3pop3', self::STATUS_NEW),
            self::STATUS_READ => Yii::t('d3pop3', self::STATUS_READ),
            self::STATUS_DELETE => Yii::t('d3pop3', self::STATUS_DELETE),
        ];
    }

}
