<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3pop3\models\base;

use Yii;

/**
 * This is the base-model class for table "d3pop3_emails".
 *
 * @property string $id
 * @property string $email_id
 * @property string $email_datetime
 * @property string $receive_datetime
 * @property string $subject
 * @property string $body
 * @property string $body_plain
 * @property string $from
 * @property string $from_name
 * @property integer $from_user_id
 * @property string $email_container_class
 * @property string $email_container_id
 *
 * @property \d3yii2\d3pop3\models\D3pop3EmailAddress[] $d3pop3EmailAddresses
 * @property \d3yii2\d3pop3\models\D3pop3EmailError[] $d3pop3EmailErrors
 * @property \d3yii2\d3pop3\models\D3pop3EmailModel[] $d3pop3EmailModels
 * @property \d3yii2\d3pop3\models\D3pop3SendReceiv[] $d3pop3SendReceivs
 * @property string $aliasModel
 */
abstract class D3pop3Email extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'd3pop3_emails';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email_datetime', 'receive_datetime'], 'safe'],
            [['receive_datetime'], 'required'],
            [['subject', 'body', 'body_plain'], 'string'],
            [['email_id'], 'string', 'max' => 1000],
            [['from', 'from_name', 'email_container_class'], 'string', 'max' => 256],
            [['from_user_id', 'email_container_id'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3pop3', 'ID'),
            'email_id' => Yii::t('d3pop3', 'Email Id'),
            'email_datetime' => Yii::t('d3pop3', 'Email Datetime'),
            'receive_datetime' => Yii::t('d3pop3', 'Received'),
            'subject' => Yii::t('d3pop3', 'Subject'),
            'body' => Yii::t('d3pop3', 'Body'),
            'body_plain' => Yii::t('d3pop3', 'Body Plain'),
            'from' => Yii::t('d3pop3', 'From'),
            'from_name' => Yii::t('d3pop3', 'From Name'),
            'from_user_id' => Yii::t('d3pop3', 'From User'),
            'email_container_class' => Yii::t('d3pop3', 'Email Container'),
            'email_container_id' => Yii::t('d3pop3', 'Email Container ID'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'email_id' => Yii::t('d3pop3', 'Email Id'),
            'receive_datetime' => Yii::t('d3pop3', 'Received'),
            'subject' => Yii::t('d3pop3', 'Subject'),
            'body' => Yii::t('d3pop3', 'Body'),
            'body_plain' => Yii::t('d3pop3', 'Body Plain'),
            'from' => Yii::t('d3pop3', 'From'),
            'from_name' => Yii::t('d3pop3', 'From Name'),
            'from_user_id' => Yii::t('d3pop3', 'From User'),
            'email_container_class' => Yii::t('d3pop3', 'Email Container'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getD3pop3EmailAddresses()
    {
        return $this->hasMany(\d3yii2\d3pop3\models\D3pop3EmailAddress::className(), ['email_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getD3pop3EmailErrors()
    {
        return $this->hasMany(\d3yii2\d3pop3\models\D3pop3EmailError::className(), ['email_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getD3pop3EmailModels()
    {
        return $this->hasMany(\d3yii2\d3pop3\models\D3pop3EmailModel::className(), ['email_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getD3pop3SendReceivs()
    {
        return $this->hasMany(\d3yii2\d3pop3\models\D3pop3SendReceiv::className(), ['email_id' => 'id']);
    }




}
