<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3pop3\models\base;

use Yii;

/**
 * This is the base-model class for table "d3pop3_emails".
 *
 * @property string $id
 * @property string $receive_datetime
 * @property string $subject
 * @property string $body
 * @property string $from
 * @property string $to
 * @property string $cc
 * @property string $email_container_class
 *
 * @property \d3yii2\d3pop3\models\D3pop3EmailModel[] $d3pop3EmailModels
 * @property string $aliasModel
 */
abstract class D3pop3Email extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'd3pop3_emails';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['receive_datetime'], 'required'],
            [['receive_datetime'], 'safe'],
            [['subject', 'body', 'to', 'cc'], 'string'],
            [['from', 'email_container_class'], 'string', 'max' => 256]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3pop3', 'ID'),
            'receive_datetime' => Yii::t('d3pop3', 'Received'),
            'subject' => Yii::t('d3pop3', 'Subject'),
            'body' => Yii::t('d3pop3', 'Body'),
            'from' => Yii::t('d3pop3', 'From'),
            'to' => Yii::t('d3pop3', 'To'),
            'cc' => Yii::t('d3pop3', 'CC'),
            'email_container_class' => Yii::t('d3pop3', 'Email Container'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'receive_datetime' => Yii::t('d3pop3', 'Received'),
            'subject' => Yii::t('d3pop3', 'Subject'),
            'body' => Yii::t('d3pop3', 'Body'),
            'from' => Yii::t('d3pop3', 'From'),
            'to' => Yii::t('d3pop3', 'To'),
            'cc' => Yii::t('d3pop3', 'CC'),
            'email_container_class' => Yii::t('d3pop3', 'Email Container'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getD3pop3EmailModels()
    {
        return $this->hasMany(\d3yii2\d3pop3\models\D3pop3EmailModel::className(), ['email_id' => 'id']);
    }




}
