<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3pop3\models\base;

use Yii;

/**
 * This is the base-model class for table "d3pop3_send_receiv".
 *
 * @property string $id
 * @property string $email_id
 * @property string $direction
 * @property integer $company_id
 * @property integer $person_id
 * @property integer $setting_id
 * @property string $status
 *
 * @property \d3yii2\d3pop3\models\D3pop3Email $email
 * @property \d3yii2\d3pop3\models\D3pop3ConnectingSetting $setting
 * @property \d3yii2\d3pop3\models\D3pPerson $person
 * @property \d3yii2\d3pop3\models\D3cCompany $company
 * @property string $aliasModel
 */
abstract class D3pop3SendReceiv extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const DIRECTION_IN = 'in';
    const DIRECTION_OUT = 'out';
    const STATUS_NEW = 'New';
    const STATUS_READ = 'Read';
    const STATUS_DELETED = 'Deleted';
    public $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'd3pop3_send_receiv';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email_id'], 'required'],
            [['email_id', 'company_id', 'person_id', 'setting_id'], 'integer'],
            [['direction', 'status'], 'string'],
            [['email_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3pop3\models\D3pop3Email::className(), 'targetAttribute' => ['email_id' => 'id']],
            [['setting_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3pop3\models\D3pop3ConnectingSettings::className(), 'targetAttribute' => ['setting_id' => 'id']],
            [['person_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3pop3\models\D3pPerson::className(), 'targetAttribute' => ['person_id' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3pop3\models\D3cCompany::className(), 'targetAttribute' => ['company_id' => 'id']],
            ['direction', 'in', 'range' => [
                    self::DIRECTION_IN,
                    self::DIRECTION_OUT,
                ]
            ],
            ['status', 'in', 'range' => [
                    self::STATUS_NEW,
                    self::STATUS_READ,
                    self::STATUS_DELETED,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3pop3', 'ID'),
            'email_id' => Yii::t('d3pop3', 'Email'),
            'direction' => Yii::t('d3pop3', 'Direction'),
            'company_id' => Yii::t('d3pop3', 'Company'),
            'person_id' => Yii::t('d3pop3', 'Person'),
            'setting_id' => Yii::t('d3pop3', 'Setting'),
            'status' => Yii::t('d3pop3', 'Status'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'email_id' => Yii::t('d3pop3', 'Email'),
            'direction' => Yii::t('d3pop3', 'Direction'),
            'company_id' => Yii::t('d3pop3', 'Company'),
            'person_id' => Yii::t('d3pop3', 'Person'),
            'setting_id' => Yii::t('d3pop3', 'Setting'),
            'status' => Yii::t('d3pop3', 'Status'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmail()
    {
        return $this->hasOne(\d3yii2\d3pop3\models\D3pop3Email::className(), ['id' => 'email_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSetting()
    {
        return $this->hasOne(\d3yii2\d3pop3\models\D3pop3ConnectingSettings::className(), ['id' => 'setting_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPerson()
    {
        return $this->hasOne(\d3yii2\d3pop3\models\D3pPerson::className(), ['id' => 'person_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\d3yii2\d3pop3\models\D3cCompany::className(), ['id' => 'company_id']);
    }




    /**
     * get column direction enum value label
     * @param string $value
     * @return string
     */
    public static function getDirectionValueLabel($value){
        $labels = self::optsDirection();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column direction ENUM value labels
     * @return array
     */
    public static function optsDirection()
    {
        return [
            self::DIRECTION_IN => Yii::t('d3pop3', self::DIRECTION_IN),
            self::DIRECTION_OUT => Yii::t('d3pop3', self::DIRECTION_OUT),
        ];
    }

    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_NEW => Yii::t('d3pop3', self::STATUS_NEW),
            self::STATUS_READ => Yii::t('d3pop3', self::STATUS_READ),
            self::STATUS_DELETED => Yii::t('d3pop3', self::STATUS_DELETED),
        ];
    }

}
