<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3pop3\models\base;

use Yii;

/**
 * This is the base-model class for table "d3pop3_connecting_settings".
 *
 * @property integer $id
 * @property integer $sys_company_id
 * @property string $model
 * @property string $model_search_field
 * @property string $search_by_email_field
 * @property string $type
 * @property string $settings
 * @property string $notes
 * @property string $aliasModel
 */
abstract class D3pop3ConnectingSettings extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const TYPE_POP3 = 'pop3';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'd3pop3_connecting_settings';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sys_company_id'], 'required'],
            [['sys_company_id'], 'integer'],
            [['model', 'type', 'settings', 'notes'], 'string'],
            [['model_search_field', 'search_by_email_field'], 'string', 'max' => 255],
            ['type', 'in', 'range' => [
                    self::TYPE_POP3,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3pop3', 'ID'),
            'sys_company_id' => Yii::t('d3pop3', 'Sys Company ID'),
            'model' => Yii::t('d3pop3', 'Model'),
            'model_search_field' => Yii::t('d3pop3', 'Model search field'),
            'search_by_email_field' => Yii::t('d3pop3', 'Search by email field'),
            'type' => Yii::t('d3pop3', 'Type'),
            'settings' => Yii::t('d3pop3', 'Settings'),
            'notes' => Yii::t('d3pop3', 'Notes'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'model' => Yii::t('d3pop3', 'Model'),
            'model_search_field' => Yii::t('d3pop3', 'Model search field'),
            'search_by_email_field' => Yii::t('d3pop3', 'Search by email field'),
            'type' => Yii::t('d3pop3', 'Type'),
            'settings' => Yii::t('d3pop3', 'Settings'),
        ]);
    }




    /**
     * get column type enum value label
     * @param string $value
     * @return string
     */
    public static function getTypeValueLabel($value){
        $labels = self::optsType();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column type ENUM value labels
     * @return array
     */
    public static function optsType()
    {
        return [
            self::TYPE_POP3 => Yii::t('d3pop3', self::TYPE_POP3),
        ];
    }

}
