<?php

namespace d3yii2\d3pop3\models;

use d3yii2\d3pop3\components\Action;
use \d3yii2\d3pop3\models\base\D3pop3ConnectingSettings as BaseD3pop3ConnectingSettings;

/**
 * This is the model class for table "d3pop3_connecting_settings".
 */
class D3pop3ConnectingSettings extends BaseD3pop3ConnectingSettings
{

    public function save($runValidation = true, $attributeNames = null)
    {
        if ($this->getIsNewRecord()) {
            return $this->insert($runValidation, $attributeNames);
        }

        return parent::save($runValidation, $attributeNames);
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($insert){
            Action::createdAccount($this->id);
        }else{
            Action::updatedAccount($this->id);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}
